### ISSUE TITLE
Breaks Netlify build

### ISSUE THREAD

**Issue by teenjuna** [JadeX/snowpack-plugin-tailwindcss-jit#5]
Hi! I tried to deploy my app to Netlify, but it failed with the following error:
```
$ npm run build
> @ build /opt/build/repo/ui
> snowpack build
/opt/build/repo/ui/node_modules/@jadex/snowpack-plugin-tailwindcss-jit/plugin.js:19
      if (!micromatch.isMatch(relativePath, tailwindConfig.purge.content ?? tailwindConfig.purge)) {
                                                                          ^
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at Object.require [as NATIVE_REQUIRE] (internal/modules/cjs/helpers.js:72:18)
    at loadPluginFromConfig (/opt/build/repo/ui/node_modules/snowpack/lib/index.js:122002:34)
    at /opt/build/repo/ui/node_modules/snowpack/lib/index.js:122032:24
    at Array.forEach (<anonymous>)
    at loadPlugins (/opt/build/repo/ui/node_modules/snowpack/lib/index.js:122029:20)
    at normalizeConfig (/opt/build/repo/ui/node_modules/snowpack/lib/index.js:122148:39)
    at createConfiguration (/opt/build/repo/ui/node_modules/snowpack/lib/index.js:122369:30)
    at Object.loadConfiguration (/opt/build/repo/ui/node_modules/snowpack/lib/index.js:122447:16)
    at async cli (/opt/build/repo/ui/node_modules/snowpack/lib/index.js:183646:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `snowpack build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/buildhome/.npm/_logs/2021-05-19T06_54_05_832Z-debug.log
```

The main error is here
```
/opt/build/repo/ui/node_modules/@jadex/snowpack-plugin-tailwindcss-jit/plugin.js:19
      if (!micromatch.isMatch(relativePath, tailwindConfig.purge.content ?? tailwindConfig.purge)) {
                                                                          ^
SyntaxError: Unexpected token '?'
```

Not sure why it doesn't like `??` operator, but I think we should fix it.

**Comment by teenjuna** [comment]
I must say that removing the plugin from `snowpack.config.js` solved this.

**Comment by Xeevis** [comment]
The nullish coalescing operator `??` was removed in [0.3.0](https://github.com/JadeX/snowpack-plugin-tailwindcss-jit/releases/tag/0.3.0) please make sure you are on the latest plugin version.

**Comment by teenjuna** [comment]
Sorry, didn't notice the update! This solves the issue.  Thanks.
